# Generated by Django 4.0.1 on 2022-02-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacexApp', '0003_rename_when_futurelaunch_launch_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futurelaunch',
            options={'ordering': ['title']},
        ),
    ]
