# Generated by Django 4.0.1 on 2022-02-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacexApp', '0006_alter_futurelaunch_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurelaunch',
            old_name='launch_site',
            new_name='launch_info',
        ),
    ]
